## Numpy :-

##### What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

----
###### Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

In [1]:
# importing the library

import numpy as np

In [3]:
# creating a list 

l1 = [1,2,3,4,5,6,7,8,9]

In [4]:
n1 = np.array(l1)

In [5]:
type(n1)

numpy.ndarray

In [6]:
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# initializing Numpy array with Zeros

n1 = np.zeros((15,15))
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [11]:
# Initializing numpy array with same number 

n1 = np.full((4,4),10)
n1

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [12]:
# Initializing numpy array with a range

n1 = np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
# Initializing numpy array with a range at the difference of 5

n1 = np.arange(10,100,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [14]:
# Initializing numpy array with a random numbers 

n1 = np.random.randint(1,100,10)
n1

array([41, 40, 98, 96, 69, 45, 77, 49, 38, 98])

In [17]:
# Numpy Shape
n1 = np.array([[1,2,3],[4,5,6]])
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
n1.shape

(2, 3)

In [21]:
# changing shape

n1.shape = (3,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Joining Numpy arrays

In [22]:
#1. vstack (vertically)

n1 = ([10,20,30])
n2 = ([40,50,60])

In [23]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [24]:
#2. hstack (horizontally)

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [25]:
#3. column stack
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

#### Numpy array mathematics

In [26]:
# adding two variables

np.sum([n1,n2])

210

In [27]:
# adding the valuses as per column -- refer vstack line for values

np.sum([n1,n2],axis=0)

array([50, 70, 90])

In [28]:
# adding the valuses as per rows -- refer vstack line for values

np.sum([n1,n2],axis=1)

array([ 60, 150])

#### Basic Mathematics in Numpy

In [29]:
n1= np.array([10,20,30])

In [32]:
# Basic addition

n1= np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [33]:
# Basic subtraction

n1= np.array([10,20,30])
n1 = n1-1
n1

array([ 9, 19, 29])

In [34]:
# Basic Multiplication

n1= np.array([10,20,30])
n1 = n1*2
n1

array([20, 40, 60])

In [35]:
# Basic Division

n1= np.array([10,20,30])
n1 = n1/2
n1

array([ 5., 10., 15.])

####  Math functions

In [42]:
n1=np.array([10,20,30,40,50,60])

In [37]:
#1. Mean
np.mean(n1)

10.0

In [40]:
#2. Median
np.median(n1)

35.0

In [43]:
#3. Std deviation
np.std(n1)

17.07825127659933